# Generated by Django 3.0.6 on 2020-06-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='histogram',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post1',
            name='result',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
