# Generated by Django 3.0.6 on 2020-06-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200611_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
