# Generated by Django 3.0.6 on 2020-05-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointOperator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Libre',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
